kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4
storageConfig:
  local:
    path: storageconfig
mirror:
  platform:
    channels:
    - name: stable-4.14
      type: ocp
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    - name: kubevirt-hyperconverged
      channels:
        - name: stable
    - name: kubernetes-nmstate-operator
      channels:
        - name: stable
    - name: cincinnati-operator
      channels:
        - name: v1
    - name: compliance-operator
      channels:
        - name: stable
    - name: mtv-operator
      channels:
        - name: release-v2.5
    - name: odf-operator
      channels:
        - name: stable-4.14
    - name: web-terminal
      channels:
        - name: fast
    - name: quay-operator
      channels:
        - name: stable-3.10
    - name: file-integrity-operator
      channels:
        - name: stable
    - name: lvms-operator
      channels:
        - name: stable-4.14
    - name: ocs-operator
      channels:
        - name: stable-4.14
    - name: local-storage-operator
      channels:
        - name: stable
  additionalImages:
  - name: registry.redhat.io/rhel9/rhel-guest-image:latest
  - name: registry.redhat.io/rhel8/rhel-guest-image:latest