kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4
mirror:
  platform:
    architectures:
      - amd64
    channels:
    - name: stable-4.15
      type: ocp
      minVersion: 4.15.12
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15
    packages:
    - name: quay-bridge-operator
      channels:
        - name: stable-3.10
    - name: quay-operator
      channels:
        - name: stable-3.10
    - name: cincinnati-operator
      channels:
        - name: v1
    - name: cluster-logging
      channels:
        - name: stable-5.8
    - name: compliance-operator
      channels:
        - name: stable
    - name: web-terminal
      channels:
        - name: fast
    - name: file-integrity-operator
      channels:
        - name: stable
    - name: ocs-operator
      channels:
        - name: stable-4.15
    - name: local-storage-operator
      channels:
        - name: stable
  additionalImages:
  - name: registry.redhat.io/rhel9/rhel-guest-image:latest
  - name: registry.redhat.io/rhel8/rhel-guest-image:latest
